defmodule Gleanex.Client.DocumentMetadata do
  @moduledoc """
  Provides struct and type for a DocumentMetadata
  """

  @type t :: %__MODULE__{
          ancestors: [Gleanex.Client.Document.t()] | nil,
          assignedTo: Gleanex.Client.Person.t() | nil,
          author: Gleanex.Client.Person.t() | nil,
          collections: [Gleanex.Client.Collection.t()] | nil,
          components: [String.t()] | nil,
          contactPerson: Gleanex.Client.Person.t() | nil,
          container: String.t() | nil,
          containerId: String.t() | nil,
          createTime: DateTime.t() | nil,
          customData: map | nil,
          datasource: String.t() | nil,
          datasourceId: String.t() | nil,
          datasourceInstance: String.t() | nil,
          documentCategory: String.t() | nil,
          documentId: String.t() | nil,
          documentIdHash: String.t() | nil,
          indexStatus: Gleanex.Client.IndexStatus.t() | nil,
          interactions: Gleanex.Client.DocumentInteractions.t() | nil,
          labels: [String.t()] | nil,
          loggingId: String.t() | nil,
          mentionedPeople: [Gleanex.Client.Person.t()] | nil,
          mimeType: String.t() | nil,
          objectType: String.t() | nil,
          owner: Gleanex.Client.Person.t() | nil,
          parentId: String.t() | nil,
          path: String.t() | nil,
          permissions: Gleanex.Client.ObjectPermissions.t() | nil,
          pins: [Gleanex.Client.PinDocument.t()] | nil,
          priority: String.t() | nil,
          shortcuts: [Gleanex.Client.Shortcut.t()] | nil,
          status: String.t() | nil,
          statusCategory: String.t() | nil,
          superContainerId: String.t() | nil,
          thumbnail: Gleanex.Client.Thumbnail.t() | nil,
          updateTime: DateTime.t() | nil,
          updatedBy: Gleanex.Client.Person.t() | nil,
          verification: Gleanex.Client.Verification.t() | nil,
          viewerInfo: Gleanex.Client.ViewerInfo.t() | nil,
          visibility: String.t() | nil,
          visitCount: Gleanex.Client.CountInfo.t() | nil
        }

  defstruct [
    :ancestors,
    :assignedTo,
    :author,
    :collections,
    :components,
    :contactPerson,
    :container,
    :containerId,
    :createTime,
    :customData,
    :datasource,
    :datasourceId,
    :datasourceInstance,
    :documentCategory,
    :documentId,
    :documentIdHash,
    :indexStatus,
    :interactions,
    :labels,
    :loggingId,
    :mentionedPeople,
    :mimeType,
    :objectType,
    :owner,
    :parentId,
    :path,
    :permissions,
    :pins,
    :priority,
    :shortcuts,
    :status,
    :statusCategory,
    :superContainerId,
    :thumbnail,
    :updateTime,
    :updatedBy,
    :verification,
    :viewerInfo,
    :visibility,
    :visitCount
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      ancestors: [{Gleanex.Client.Document, :t}],
      assignedTo: {Gleanex.Client.Person, :t},
      author: {Gleanex.Client.Person, :t},
      collections: [{Gleanex.Client.Collection, :t}],
      components: [:string],
      contactPerson: {Gleanex.Client.Person, :t},
      container: :string,
      containerId: :string,
      createTime: {:string, "date-time"},
      customData: :map,
      datasource: :string,
      datasourceId: :string,
      datasourceInstance: :string,
      documentCategory: :string,
      documentId: :string,
      documentIdHash: :string,
      indexStatus: {Gleanex.Client.IndexStatus, :t},
      interactions: {Gleanex.Client.DocumentInteractions, :t},
      labels: [:string],
      loggingId: :string,
      mentionedPeople: [{Gleanex.Client.Person, :t}],
      mimeType: :string,
      objectType: :string,
      owner: {Gleanex.Client.Person, :t},
      parentId: :string,
      path: :string,
      permissions: {Gleanex.Client.ObjectPermissions, :t},
      pins: [{Gleanex.Client.PinDocument, :t}],
      priority: :string,
      shortcuts: [{Gleanex.Client.Shortcut, :t}],
      status: :string,
      statusCategory: :string,
      superContainerId: :string,
      thumbnail: {Gleanex.Client.Thumbnail, :t},
      updateTime: {:string, "date-time"},
      updatedBy: {Gleanex.Client.Person, :t},
      verification: {Gleanex.Client.Verification, :t},
      viewerInfo: {Gleanex.Client.ViewerInfo, :t},
      visibility:
        {:enum,
         [
           "PRIVATE",
           "SPECIFIC_PEOPLE_AND_GROUPS",
           "DOMAIN_LINK",
           "DOMAIN_VISIBLE",
           "PUBLIC_LINK",
           "PUBLIC_VISIBLE"
         ]},
      visitCount: {Gleanex.Client.CountInfo, :t}
    ]
  end
end
