defmodule Gleanex.Client.FeedEntry do
  @moduledoc """
  Provides struct and type for a FeedEntry
  """

  @type t :: %__MODULE__{
          activities: [Gleanex.Client.UserActivity.t()] | nil,
          announcement: Gleanex.Client.Announcement.t() | nil,
          app: Gleanex.Client.AppResult.t() | nil,
          chatSuggestion: Gleanex.Client.ChatSuggestion.t() | nil,
          collection: Gleanex.Client.Collection.t() | nil,
          collectionItem: Gleanex.Client.CollectionItem.t() | nil,
          createdBy: Gleanex.Client.Person.t() | nil,
          digest: Gleanex.Client.Digest.t() | nil,
          document: Gleanex.Client.Document.t() | nil,
          documentVisitorCount: Gleanex.Client.CountInfo.t() | nil,
          entryId: String.t() | nil,
          event: Gleanex.Client.CalendarEvent.t() | nil,
          justification: String.t() | nil,
          justificationType: String.t() | nil,
          person: Gleanex.Client.Person.t() | nil,
          promptTemplate: Gleanex.Client.PromptTemplateResult.t() | nil,
          thumbnail: Gleanex.Client.Thumbnail.t() | nil,
          title: String.t(),
          trackingToken: String.t() | nil,
          uiConfig: Gleanex.Client.FeedEntryUiConfig.t() | nil,
          viewUrl: String.t() | nil,
          workflow: Gleanex.Client.WorkflowResult.t() | nil
        }

  defstruct [
    :activities,
    :announcement,
    :app,
    :chatSuggestion,
    :collection,
    :collectionItem,
    :createdBy,
    :digest,
    :document,
    :documentVisitorCount,
    :entryId,
    :event,
    :justification,
    :justificationType,
    :person,
    :promptTemplate,
    :thumbnail,
    :title,
    :trackingToken,
    :uiConfig,
    :viewUrl,
    :workflow
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      activities: [{Gleanex.Client.UserActivity, :t}],
      announcement: {Gleanex.Client.Announcement, :t},
      app: {Gleanex.Client.AppResult, :t},
      chatSuggestion: {Gleanex.Client.ChatSuggestion, :t},
      collection: {Gleanex.Client.Collection, :t},
      collectionItem: {Gleanex.Client.CollectionItem, :t},
      createdBy: {Gleanex.Client.Person, :t},
      digest: {Gleanex.Client.Digest, :t},
      document: {Gleanex.Client.Document, :t},
      documentVisitorCount: {Gleanex.Client.CountInfo, :t},
      entryId: :string,
      event: {Gleanex.Client.CalendarEvent, :t},
      justification: :string,
      justificationType:
        {:enum,
         [
           "FREQUENTLY_ACCESSED",
           "RECENTLY_ACCESSED",
           "TRENDING_DOCUMENT",
           "VERIFICATION_REMINDER",
           "SUGGESTED_DOCUMENT",
           "EMPTY_STATE_SUGGESTION",
           "FRECENCY_SCORED",
           "SERVER_GENERATED",
           "USE_CASE",
           "UPDATE_SINCE_LAST_VIEW",
           "RECENTLY_STARTED",
           "EVENT",
           "USER_MENTION",
           "ANNOUNCEMENT",
           "EXTERNAL_ANNOUNCEMENT",
           "POPULARITY_BASED_TRENDING",
           "COMPANY_RESOURCE",
           "EVENT_DOCUMENT_FROM_CONTENT",
           "EVENT_DOCUMENT_FROM_SEARCH",
           "VISIT_AFFINITY_SCORED",
           "SUGGESTED_APP",
           "SUGGESTED_PERSON",
           "ACTIVITY_HIGHLIGHT",
           "SAVED_SEARCH",
           "SUGGESTED_CHANNEL",
           "PEOPLE_CELEBRATIONS",
           "SOCIAL_LINK",
           "ZERO_STATE_CHAT_SUGGESTION",
           "ZERO_STATE_CHAT_TOOL_SUGGESTION",
           "ZERO_STATE_PROMPT_TEMPLATE_SUGGESTION",
           "ZERO_STATE_STATIC_WORKFLOW_SUGGESTION",
           "ZERO_STATE_AGENT_SUGGESTION",
           "PERSONALIZED_CHAT_SUGGESTION",
           "DAILY_DIGEST",
           "PODCAST",
           "TASK",
           "PLAN_MY_DAY",
           "END_MY_DAY",
           "STARTER_KIT_EXTENSION",
           "STARTER_KIT_ORG_CHART",
           "STARTER_KIT_ADD_DOC",
           "MEETING_RECAP",
           "ACTIVE_DISCUSSION",
           "MID_DAY_CATCH_UP",
           "QUERY_SUGGESTION",
           "COWORK_CUJ_PROMO",
           "CARD_STACK_PROMO",
           "WEEKLY_MEETINGS",
           "FOLLOW_UP",
           "MILESTONE_TIMELINE_CHECK",
           "PROJECT_DISCUSSION_DIGEST",
           "PROJECT_FOCUS_BLOCK",
           "PROJECT_NEXT_STEP",
           "DEMO_CARD",
           "OOO_PLANNER",
           "OOO_CATCH_UP",
           "ADMIN_HEALTH_CENTER"
         ]},
      person: {Gleanex.Client.Person, :t},
      promptTemplate: {Gleanex.Client.PromptTemplateResult, :t},
      thumbnail: {Gleanex.Client.Thumbnail, :t},
      title: :string,
      trackingToken: :string,
      uiConfig: {Gleanex.Client.FeedEntryUiConfig, :t},
      viewUrl: :string,
      workflow: {Gleanex.Client.WorkflowResult, :t}
    ]
  end
end
