defmodule Gleanex.Client.PersonMetadata do
  @moduledoc """
  Provides struct and type for a PersonMetadata
  """

  @type t :: %__MODULE__{
          aliasEmails: [String.t()] | nil,
          badges: [Gleanex.Client.Badge.t()] | nil,
          bannerUrl: String.t() | nil,
          bio: String.t() | nil,
          businessUnit: String.t() | nil,
          busyEvents: [Gleanex.Client.AnonymousEvent.t()] | nil,
          customFields: [Gleanex.Client.CustomFieldData.t()] | nil,
          datasourceProfile: [Gleanex.Client.DatasourceProfile.t()] | nil,
          department: String.t() | nil,
          departmentCount: integer | nil,
          directReportsCount: integer | nil,
          email: String.t() | nil,
          endDate: Date.t() | nil,
          externalProfileLink: String.t() | nil,
          firstName: String.t() | nil,
          inviteInfo: Gleanex.Client.InviteInfo.t() | nil,
          isOrgRoot: boolean | nil,
          isSignedUp: boolean | nil,
          lastExtensionUse: DateTime.t() | nil,
          lastName: String.t() | nil,
          location: String.t() | nil,
          loggingId: String.t() | nil,
          managementChain: [Gleanex.Client.Person.t()] | nil,
          manager: Gleanex.Client.Person.t() | nil,
          orgSizeCount: integer | nil,
          peopleDistance: [Gleanex.Client.PersonDistance.t()] | nil,
          permissions: Gleanex.Client.Permissions.t() | nil,
          phone: String.t() | nil,
          photoUrl: String.t() | nil,
          preferredName: String.t() | nil,
          profileBoolSettings: map | nil,
          pronoun: String.t() | nil,
          querySuggestions: Gleanex.Client.QuerySuggestionList.t() | nil,
          reports: [Gleanex.Client.Person.t()] | nil,
          socialNetwork: [Gleanex.Client.SocialNetwork.t()] | nil,
          startDate: Date.t() | nil,
          startDatePercentile: number | nil,
          structuredLocation: Gleanex.Client.StructuredLocation.t() | nil,
          teams: [Gleanex.Client.PersonTeam.t()] | nil,
          timezone: String.t() | nil,
          timezoneIANA: String.t() | nil,
          timezoneOffset: integer | nil,
          title: String.t() | nil,
          type: String.t() | nil,
          uneditedPhotoUrl: String.t() | nil
        }

  defstruct [
    :aliasEmails,
    :badges,
    :bannerUrl,
    :bio,
    :businessUnit,
    :busyEvents,
    :customFields,
    :datasourceProfile,
    :department,
    :departmentCount,
    :directReportsCount,
    :email,
    :endDate,
    :externalProfileLink,
    :firstName,
    :inviteInfo,
    :isOrgRoot,
    :isSignedUp,
    :lastExtensionUse,
    :lastName,
    :location,
    :loggingId,
    :managementChain,
    :manager,
    :orgSizeCount,
    :peopleDistance,
    :permissions,
    :phone,
    :photoUrl,
    :preferredName,
    :profileBoolSettings,
    :pronoun,
    :querySuggestions,
    :reports,
    :socialNetwork,
    :startDate,
    :startDatePercentile,
    :structuredLocation,
    :teams,
    :timezone,
    :timezoneIANA,
    :timezoneOffset,
    :title,
    :type,
    :uneditedPhotoUrl
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      aliasEmails: [:string],
      badges: [{Gleanex.Client.Badge, :t}],
      bannerUrl: {:string, "url"},
      bio: :string,
      businessUnit: :string,
      busyEvents: [{Gleanex.Client.AnonymousEvent, :t}],
      customFields: [{Gleanex.Client.CustomFieldData, :t}],
      datasourceProfile: [{Gleanex.Client.DatasourceProfile, :t}],
      department: :string,
      departmentCount: :integer,
      directReportsCount: :integer,
      email: :string,
      endDate: {:string, "date"},
      externalProfileLink: :string,
      firstName: :string,
      inviteInfo: {Gleanex.Client.InviteInfo, :t},
      isOrgRoot: :boolean,
      isSignedUp: :boolean,
      lastExtensionUse: {:string, "date-time"},
      lastName: :string,
      location: :string,
      loggingId: :string,
      managementChain: [{Gleanex.Client.Person, :t}],
      manager: {Gleanex.Client.Person, :t},
      orgSizeCount: :integer,
      peopleDistance: [{Gleanex.Client.PersonDistance, :t}],
      permissions: {Gleanex.Client.Permissions, :t},
      phone: :string,
      photoUrl: {:string, "url"},
      preferredName: :string,
      profileBoolSettings: :map,
      pronoun: :string,
      querySuggestions: {Gleanex.Client.QuerySuggestionList, :t},
      reports: [{Gleanex.Client.Person, :t}],
      socialNetwork: [{Gleanex.Client.SocialNetwork, :t}],
      startDate: {:string, "date"},
      startDatePercentile: {:number, "float"},
      structuredLocation: {Gleanex.Client.StructuredLocation, :t},
      teams: [{Gleanex.Client.PersonTeam, :t}],
      timezone: :string,
      timezoneIANA: :string,
      timezoneOffset: {:integer, "int64"},
      title: :string,
      type: {:enum, ["FULL_TIME", "CONTRACTOR", "NON_EMPLOYEE", "FORMER_EMPLOYEE"]},
      uneditedPhotoUrl: {:string, "url"}
    ]
  end
end
