name: Publish to Hex.pm

permissions:
  contents: read

on:
  release:
    types: [released]

jobs:
  publish:
    name: Build and publish to hex.pm
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Setup Elixir
      uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
      with:
        version-file: '.tool-versions'
        version-type: 'strict'

    - name: Restore dependencies cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: deps
        key: ${{ runner.os }}-publish-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-publish-mix-

    - name: Install deps
      run: mix deps.get

    - name: Publish to Hex.pm
      run: mix hex.publish --yes
